Update build_loop.yml

diff --git a/.github/workflows/build_loop.yml b/.github/workflows/build_loop.yml
--- a/.github/workflows/build_loop.yml
+++ b/.github/workflows/build_loop.yml
@@ -1,12 +1,10 @@
 name: 4. Build Loop
 run-name: Build Loop (${{ github.ref_name }})
-
 on:
   workflow_dispatch:
 
   ## Remove the "#" sign from the beginning of the line below to get automated builds on push (code changes in your repository)
-  push:
-    branches: [ main ]
+  #push:
 
   # Automated builds now include automatic certificate update - the nuke certs part of that process could
   #   affect other OS apps if run simultaneously.
@@ -17,51 +15,21 @@ on:
 
 env:
   UPSTREAM_REPO: LoopKit/LoopWorkspace
-  UPSTREAM_BRANCH: ${{ github.ref_name }}
-  TARGET_BRANCH: ${{ github.ref_name }}
+  UPSTREAM_BRANCH: ${{ github.ref_name }} # branch on upstream repository to sync from (replace with specific branch name if needed)
+  TARGET_BRANCH: ${{ github.ref_name }} # target branch on fork to be kept in sync, and target branch on upstream to be kept alive (replace with specific branch name if needed)
   ALIVE_BRANCH_MAIN: alive-main
   ALIVE_BRANCH_DEV: alive-dev
-  # . ENABLE_NUKE_CERTS: ${{ secrets.ENABLE_NUKE_CERTS }}
-  # . FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
-  # . FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
-  
+
 jobs:
   # Checks if Distribution certificate is present and valid, optionally nukes and
   # creates new certs if the repository variable ENABLE_NUKE_CERTS == 'true'
   check_certs: 
-    name: Check Certificates
+    name: Check certificates
     uses: ./.github/workflows/create_certs.yml
     secrets: inherit
 
-  # Step 2: Optionally nuke certificates if enabled via secrets
-  # .nuke_certs:
-    # . name: Nuke Distribution Certificates (conditionally)
-    # . needs: check_certs
-    # . runs-on: ubuntu-latest
-    # . env:
-      # . FASTLANE_USER: ${{ secrets.FASTLANE_USER }}         # deine Apple-ID (z. B. manfred@icloud.com)
-     # .  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }} # app-spezifisches Passwort von appleid.apple.com
-     # .  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}       # optional: Passwort für verschlüsseltes match-Repo
-   # . steps:
-      # . - name: Checkout repository
-      # .   uses: actions/checkout@v4
-
-      # . - name: Set up Ruby and Bundler
-      # .   uses: ruby/setup-ruby@v1
-       # .  with:
-       # .    ruby-version: '3.1'
-       # .    bundler-cache: true
-
-     # . - name: Nuke distribution certificates via Fastlane
-     # .    if: env.ENABLE_NUKE_CERTS == 'true'
-      # .   run: |
-      # .     echo "Nuking distribution certificates..."
-      # .     bundle exec fastlane match nuke distribution --force --skip_confirmation 
-        
-        
   # Checks if GH_PAT holds workflow permissions
   # Checks for existence of alive branch; if non-existent creates it
-  
   check_alive_and_permissions:
     needs: check_certs
     runs-on: ubuntu-latest
@@ -81,11 +49,11 @@ jobs:
 
           if [[ $PERMISSIONS =~ "workflow" || $PERMISSIONS == "" ]]; then
             echo "GH_PAT holds workflow permissions or is fine-grained PAT."
-            echo "has_permission=true" >> $GITHUB_OUTPUT
+            echo "has_permission=true" >> $GITHUB_OUTPUT # Set WORKFLOW_PERMISSION to false.
           else 
             echo "GH_PAT lacks workflow permissions."
             echo "Automated build features will be skipped!"
-            echo "has_permission=false" >> $GITHUB_OUTPUT
+            echo "has_permission=false" >> $GITHUB_OUTPUT # Set WORKFLOW_PERMISSION to false.
           fi
 
       - name: Check for alive branches
@@ -323,7 +291,8 @@ jobs:
           if [ -f "$TABLE_PRINTER_PATH" ]; then
             sed -i "" "/puts(Terminal::Table.new(params))/d" "$TABLE_PRINTER_PATH"
           else
-            echo "Warning: table_printer.rb not found. Skipping patch."
+            echo "table_printer.rb not found"
+            exit 1
           fi
 
       # Install project dependencies
